services:
  - type: web
    name: mlsc-website
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /team
        destination: /index.html
      - type: rewrite
        source: /about
        destination: /index.html
      - type: rewrite
        source: /events
        destination: /index.html
      - type: rewrite
        source: /Events
        destination: /index.html
      - type: rewrite
        source: /scheduler
        destination: /index.html
      - type: rewrite
        source: /works
        destination: /index.html
      - type: rewrite
        source: /Projects
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
